services:
  backend:
    image: nobugsme/nbank:with_username_error_fix
    ports:
      - "4111:4111"
    networks:
      - nbank-network

  frontend:
    image: nobugsme/nbank-ui:with_nginx
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nbank-network

  selenoid:
    image: aerokube/selenoid:latest
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/selenoid/:ro
    command: [ "-container-network", "nbank-network" ]
    depends_on:
      - frontend
    networks:
      - nbank-network

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    depends_on:
      - selenoid
    networks:
      - nbank-network
  tests:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: nbank-tests
    environment:
      TEST_PROFILE: api
      BASEAPIURL: http://backend:4111
      BASEUIURL: http://frontend:3000
    volumes:
      - ../../test-output/logs:/app/logs
      - ../../test-output/results:/app/target/surefire-reports
      - ../../test-output/reports:/app/target/site
    depends_on:
      - backend
      - frontend
      - selenoid
    networks:
      - nbank-network

networks:
  nbank-network:
    name: nbank-network