services:
  backend:
    image: nobugsme/nbank:with_username_error_fix
    ports:
      - "4111:4111"
    networks:
      - nbank-network

  frontend:
    image: nobugsme/nbank-ui:latest
    expose:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nbank-network

  selenoid:
    image: aerokube/selenoid:latest
    platform: linux/amd64
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/browsers.json:/etc/selenoid/browsers.json:ro
    command: [ "-container-network","nbank-network" ]
    depends_on:
      - frontend
    networks:
      - nbank-network

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    platform: linux/amd64
    ports:
      - "6567:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    depends_on:
      - selenoid
    networks:
      - nbank-network

networks:
  nbank-network:
    name: nbank-network
