name: Build Docker and Run Tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build Docker image, run tests, and push
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: n-bank-test-image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-key: |
            ${{ runner.os }}-maven-

      - name: Get commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up services
        run: |
          pushd infrastructure/docker_compose
          bash restart_docker.sh
          popd

      - name: Run Maven tests
        run: ./mvnw clean test -q
        env:
          APIBASEURL: http://localhost:4444
          UIBASEURL: http://frontend

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ env.COMMIT_HASH }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag $IMAGE_NAME:${{ env.COMMIT_HASH }} ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ env.COMMIT_HASH }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ env.COMMIT_HASH }}
