name: Run tests

# trigger
on: [ push, workflow_dispatch ]

jobs:
  run-tests:
    name: Set up services and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os}}-maven-${{hashFiles('**/pom.xml')}}
          restore-key: |
            ${{ runner.os}}-maven-

      - name: Set up services
        run: |
          pushd infrastructure/docker_compose
          bash restart_docker.sh
          popd
      - name: Run test
        run: ./mvnw clean test -q
        env:
          APIBASEURL: http://localhost:4444
          UIBASEURL: http://frontend

      - name: Get commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t n-bank-test-image:${{ env.COMMIT_HASH }} .

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/n-bank-test-image:${{ env.COMMIT_HASH }}
